import os
from os import system, name 
from time import sleep
print("ASCII art that I can generate")
print("exit")
print("-impostor")
print("-crewmate")
print("-cake")
anim = input("Select one")
if str(anim) == "exit":
    os.system("main.py")
if str(anim) == "impostor":
    name = input("Give nickname to impostor")
    icount = input("How many impostors left?")
    print(".         •    　　。   .")
    print("　　　.　　　 　　.           .  ")
    print(".　　 。　　　　　 ඞ 。 . 　　 • 　　　　•")
    print("　　ﾟ {} was An Impostor.　 。　.".format(name))
    print("　　'　　　     {} Impostors remain 　 　　。".format(icount))
    print("　ﾟ　　　.　　　. ,　　　　.　 .")
    print("Copy and paste (it can look weird but i promise it will work)")
    os.system("ascii.py")
if str(anim) == "crewmate":
    name = input("Give nickname to crewmate")
    icount = input("How many impostors left?")
    print(".         •    　　。   .")
    print("　　　.　　　 　　.           .  ")
    print(".　　 。　　　　　 ඞ 。 . 　　 • 　　　　•")
    print("　　ﾟ {} was not An Impostor.　 。　.".format(name))
    print("　　'　　　     {} Impostors remain 　 　　。".format(icount))
    print("　ﾟ　　　.　　　. ,　　　　.　 .")
    print("Copy and paste (it can look weird but i promise it will work)")
    os.system("ascii.py")
if str(anim) == "cake":
    name = input("Give name of the person that have birthday")
    print("                 ,")
    print("                (_)")
    print("                |-|")
    print("                | |")
    print("                | |")
    print("               .| |.")
    print("              |'---'|")
    print("              |~  ~~|")
    print("          .-@'|  ~  |'@-.")
    print("         (@    '---'    @)")
    print("         |'-@..__@__..@-'|")
    print("      () |~  ~ ~ ~     ~ | ()")
    print("     .||'| ~() ~   ~ ()~ |'||.")
    print("    ( || @'-||.__~__.||-'@ || )")
    print("    |'-.._  ||   @   ||  _..-'|")
    print("    |~ ~  '''---------'''  ~  |")
    print("    |  ~  ~  H A P P Y ~  ~  ~|")
    print("    | ~   B I R T H D A Y ~ ~ |")
    print("     '-.._{}_..-'".format(name))
    print("          '''---------'''")
    print("Copy and paste (it can look weird but i promise it will work)")
    os.system("ascii.py")