name = input("Give the name of the coded file (can and even MUST include .txt at the end if original file include it)")
import os
with open(str(name)) as f:
    actualtext = f.read()
print("Decoding")
actualtext = str(actualtext).replace("0","a")
actualtext = str(actualtext).replace("9","b")
actualtext = str(actualtext).replace("8","c")
actualtext = str(actualtext).replace("7","d")
actualtext = str(actualtext).replace("6","e")
actualtext = str(actualtext).replace("5","f")
actualtext = str(actualtext).replace("4","g")
actualtext = str(actualtext).replace("3","h")
actualtext = str(actualtext).replace("2","i")
actualtext = str(actualtext).replace("1","j")
actualtext = str(actualtext).replace("~","k")
actualtext = str(actualtext).replace("-","l")
actualtext = str(actualtext).replace("|","m")
actualtext = str(actualtext).replace("=","n")
actualtext = str(actualtext).replace("+","o")
actualtext = str(actualtext).replace("_","p")
actualtext = str(actualtext).replace("'","r")
actualtext = str(actualtext).replace("/","s")
actualtext = str(actualtext).replace("`","t")
actualtext = str(actualtext).replace("*","u")
actualtext = str(actualtext).replace("(","w")
actualtext = str(actualtext).replace(")","y")
actualtext = str(actualtext).replace("&","x")
actualtext = str(actualtext).replace("^","z")
actualtext = str(actualtext).replace("$","q")
f = open(str(name),"w")
f.write(actualtext)
f.close()
print("Decoded")
os.system("menucoder.py")